lines = [
"",
"// ─── Main Settings Page ───────────────────────────────────────────────────────",
"export default function SettingsPage() {",
"  const { data: session } = useSession()",
"  const [view, setView] = useState('OVERVIEW')",
"  const [saving, setSaving] = useState(false)",
"  const [hotelInfo, setHotelInfo] = useState<HotelInfo>({ name: '', description: '', address: '', phone: '', email: '', plan: 'BASE', features: [], planExpiresAt: null, ranking: 0 })",
"  const [selectedRole, setSelectedRole] = useState('MANAGER')",
"  const [permissions, setPermissions] = useState<Record<string, boolean>>({})",
"  const [notif, setNotif] = useState({ smsAlerts: false, pushNotifications: true, emailAlerts: true, bookingConfirmation: true, checkoutReminder: true, serviceUpdates: true })",
"  const [retention, setRetention] = useState({ guestProfiles: '3_YEARS', financials: '7_YEARS', serviceLogs: '1_YEAR', legalHoldMode: false })",
"",
"  const INTEGRATIONS = [",
"    { id: 'booking_com', name: 'Booking.com',  type: 'OTA Channel',      status: 'NOT_CONNECTED' },",
"    { id: 'expedia',     name: 'Expedia',       type: 'OTA Channel',      status: 'NOT_CONNECTED' },",
"    { id: 'airbnb',      name: 'Airbnb',        type: 'Travel & Booking', status: 'NOT_CONNECTED' },",
"    { id: 'makemytrip',  name: 'MakeMyTrip',    type: 'OTA Channel',      status: 'NOT_CONNECTED' },",
"    { id: 'razorpay',    name: 'Razorpay',      type: 'Payment Gateway',  status: 'CONNECTED' },",
"    { id: 'twilio',      name: 'Twilio',        type: 'SMS / WhatsApp',   status: 'CONNECTED' },",
"  ]",
"",
"  const currentPropertyId = useMemo(() => session?.user?.role === 'SUPER_ADMIN' ? getAdminContext()?.propertyId : session?.user?.propertyId, [session])",
"",
"  const fetchProperty = useCallback(async () => {",
"    if (!currentPropertyId || currentPropertyId === 'ALL') return",
"    try {",
"      const r = await fetch(`/api/admin/settings/property?propertyId=${currentPropertyId}`)",
"      const d = await r.json()",
"      if (d.success && d.property) setHotelInfo(d.property)",
"    } catch { /* silent */ }",
"  }, [currentPropertyId])",
"",
"  const fetchRoles = useCallback(async () => {",
"    if (!currentPropertyId || currentPropertyId === 'ALL') return",
"    try {",
"      const r = await fetch(`/api/admin/settings/roles?propertyId=${currentPropertyId}`)",
"      const d = await r.json()",
"      if (d.success) {",
"        const cur = (d.rolePermissions || []).find((rp: any) => rp.role === selectedRole)",
"        setPermissions(cur?.permissions || {})",
"      }",
"    } catch { /* silent */ }",
"  }, [currentPropertyId, selectedRole])",
"",
"  useEffect(() => { fetchProperty() }, [fetchProperty])",
"  useEffect(() => { fetchRoles() }, [fetchRoles])",
"",
"  const saveBranding = async () => {",
"    if (!currentPropertyId || currentPropertyId === 'ALL') { toast.error('Select a hotel first'); return }",
"    setSaving(true)",
"    try {",
"      const r = await fetch('/api/admin/settings/property', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ propertyId: currentPropertyId, ...hotelInfo }) })",
"      const d = await r.json()",
"      if (d.success) toast.success('Hotel info saved')",
"      else toast.error(d.error ?? 'Failed to save')",
"    } catch { toast.error('Connection error') } finally { setSaving(false) }",
"  }",
"",
"  const saveRoles = async () => {",
"    if (!currentPropertyId || currentPropertyId === 'ALL') { toast.error('Select a hotel first'); return }",
"    setSaving(true)",
"    try {",
"      const r = await fetch('/api/admin/settings/roles', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ propertyId: currentPropertyId, role: selectedRole, permissions }) })",
"      const d = await r.json()",
"      if (d.success) toast.success('Permissions saved')",
"      else toast.error(d.error ?? 'Failed to save')",
"    } catch { toast.error('Connection error') } finally { setSaving(false) }",
"  }",
"",
"  const handleUpgrade = async (plan: PlanDef) => {",
"    if (!currentPropertyId || currentPropertyId === 'ALL') { toast.error('Select a hotel first'); return }",
"    setSaving(true)",
"    try {",
"      const oRes = await fetch('/api/admin/subscription/upgrade', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'CREATE_ORDER', planId: plan.plan, propertyId: currentPropertyId }) })",
"      const oData = await oRes.json()",
"      if (!oData.success) throw new Error(oData.error || 'Order failed')",
"      const opts = {",
"        key: oData.key, amount: oData.amount, currency: oData.currency,",
"        name: 'Zenbourg', description: `Upgrade to ${plan.displayName}`, order_id: oData.orderId,",
"        handler: async (resp: any) => {",
"          try {",
"            const vRes = await fetch('/api/admin/subscription/upgrade', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'VERIFY_PAYMENT', planId: plan.plan, propertyId: currentPropertyId, razorpayData: resp }) })",
"            const vData = await vRes.json()",
"            if (vData.success) { setHotelInfo(p => ({ ...p, plan: plan.plan })); toast.success(`Upgraded to ${plan.displayName}!`) }",
"            else toast.error(vData.error ?? 'Verification failed')",
"          } catch { toast.error('Verification error') } finally { setSaving(false) }",
"        },",
"        prefill: { name: session?.user?.name, email: session?.user?.email },",
"        theme: { color: '#4A9EFF' }, modal: { ondismiss: () => setSaving(false) },",
"      }",
"      new (window as any).Razorpay(opts).open()",
"    } catch (e: any) { toast.error(e.message || 'Upgrade failed'); setSaving(false) }",
"  }",
"",
"  const ic = 'w-full bg-surface-light border border-border rounded-xl px-4 py-2.5 text-sm text-white focus:ring-1 focus:ring-primary outline-none transition-all'",
"  const lc = 'text-xs font-semibold text-text-secondary block mb-1.5'",
]

with open('app/admin/settings/page.tsx', 'a', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')
print(f'Main component state: {len(lines)} lines')
