lines = [
"",
"  const renderView = () => {",
"    if (view === 'BRANDING') return (",
"      <div className=\"space-y-6\">",
"        <div className=\"bg-surface border border-border rounded-2xl p-6 space-y-5\">",
"          <div className=\"flex items-center justify-between\">",
"            <div><h3 className=\"text-base font-semibold text-white\">Hotel Information</h3><p className=\"text-xs text-text-secondary mt-0.5\">Update your hotel name, contact details and description</p></div>",
"            <Button onClick={saveBranding} loading={saving} variant=\"primary\" className=\"text-sm\"><Save className=\"w-4 h-4 mr-2\" />Save</Button>",
"          </div>",
"          <div className=\"grid grid-cols-1 md:grid-cols-2 gap-4\">",
"            <div><label className={lc}>Hotel Name</label><input value={hotelInfo.name} onChange={e => setHotelInfo(p => ({ ...p, name: e.target.value }))} className={ic} placeholder=\"e.g. Grand Palace Hotel\" /></div>",
"            <div><label className={lc}>Email</label><input type=\"email\" value={hotelInfo.email} onChange={e => setHotelInfo(p => ({ ...p, email: e.target.value }))} className={ic} placeholder=\"admin@hotel.com\" /></div>",
"            <div><label className={lc}>Phone</label><input value={hotelInfo.phone} onChange={e => setHotelInfo(p => ({ ...p, phone: e.target.value }))} className={ic} placeholder=\"+91 98765 43210\" /></div>",
"            <div><label className={lc}>Address</label><input value={hotelInfo.address} onChange={e => setHotelInfo(p => ({ ...p, address: e.target.value }))} className={ic} placeholder=\"Street, City, State\" /></div>",
"          </div>",
"          <div><label className={lc}>Description</label><textarea rows={3} value={hotelInfo.description} onChange={e => setHotelInfo(p => ({ ...p, description: e.target.value }))} className={cn(ic, 'resize-none')} placeholder=\"Brief description of your hotel...\" /></div>",
"        </div>",
"      </div>",
"    )",
"",
"    if (view === 'ROLES') return (",
"      <div className=\"space-y-6\">",
"        <div className=\"bg-surface border border-border rounded-2xl p-6\">",
"          <div className=\"flex items-center justify-between mb-5\">",
"            <div><h3 className=\"text-base font-semibold text-white\">Roles & Permissions</h3><p className=\"text-xs text-text-secondary mt-0.5\">Control what each staff role can access</p></div>",
"            <Button onClick={saveRoles} loading={saving} variant=\"primary\" className=\"text-sm\"><Save className=\"w-4 h-4 mr-2\" />Save</Button>",
"          </div>",
"          <div className=\"flex gap-2 flex-wrap mb-6\">",
"            {ROLES.map(r => (",
"              <button key={r.id} onClick={() => setSelectedRole(r.id)} className={cn('px-4 py-2 rounded-xl text-sm font-medium transition-all', selectedRole === r.id ? 'bg-primary text-white' : 'bg-surface-light text-text-secondary hover:text-white border border-border')}>",
"                {r.label}",
"              </button>",
"            ))}",
"          </div>",
"          <div className=\"space-y-6\">",
"            {PERMISSIONS_SCHEMA.map(mod => (",
"              <div key={mod.id}>",
"                <p className=\"text-xs font-bold text-text-tertiary uppercase tracking-wider mb-3\">{mod.label}</p>",
"                <div className=\"grid grid-cols-1 md:grid-cols-2 gap-3\">",
"                  {mod.permissions.map(perm => (",
"                    <div key={perm.id} className=\"flex items-center justify-between p-4 bg-surface-light border border-border rounded-xl\">",
"                      <div><p className=\"text-sm font-medium text-white\">{perm.label}</p><p className=\"text-xs text-text-secondary mt-0.5\">{perm.desc}</p></div>",
"                      <Switch checked={!!permissions[perm.id]} onChange={() => setPermissions(p => ({ ...p, [perm.id]: !p[perm.id] }))} />",
"                    </div>",
"                  ))}",
"                </div>",
"              </div>",
"            ))}",
"          </div>",
"        </div>",
"      </div>",
"    )",
"",
"    if (view === 'FINANCIAL') return <FinancialView propertyId={currentPropertyId} />",
"",
"    if (view === 'OPS') return (",
"      <div className=\"space-y-6\">",
"        <div className=\"bg-surface border border-border rounded-2xl p-6 space-y-5\">",
"          <div><h3 className=\"text-base font-semibold text-white\">Notification Settings</h3><p className=\"text-xs text-text-secondary mt-0.5\">Control which alerts are sent to staff and guests</p></div>",
"          <div className=\"space-y-3\">",
"            {[",
"              { id: 'smsAlerts',           label: 'SMS Alerts',              desc: 'Send SMS for bookings and service updates' },",
"              { id: 'pushNotifications',   label: 'Push Notifications',      desc: 'In-app push alerts for staff' },",
"              { id: 'emailAlerts',         label: 'Email Alerts',            desc: 'Email notifications for important events' },",
"              { id: 'bookingConfirmation', label: 'Booking Confirmation',    desc: 'Auto-send confirmation to guests on booking' },",
"              { id: 'checkoutReminder',    label: 'Checkout Reminder',       desc: 'Remind guests 1 hour before checkout' },",
"              { id: 'serviceUpdates',      label: 'Service Request Updates', desc: 'Notify guests when their request is completed' },",
"            ].map(n => (",
"              <div key={n.id} className=\"flex items-center justify-between p-4 bg-surface-light border border-border rounded-xl\">",
"                <div><p className=\"text-sm font-medium text-white\">{n.label}</p><p className=\"text-xs text-text-secondary mt-0.5\">{n.desc}</p></div>",
"                <Switch checked={!!(notif as any)[n.id]} onChange={() => setNotif(p => ({ ...p, [n.id]: !(p as any)[n.id] }))} />",
"              </div>",
"            ))}",
"          </div>",
"          <Button onClick={() => toast.success('Notification settings saved')} variant=\"primary\" className=\"text-sm\"><Save className=\"w-4 h-4 mr-2\" />Save Settings</Button>",
"        </div>",
"      </div>",
"    )",
"",
"    if (view === 'SUBSCRIPTION') return (",
"      <SubscriptionView propertyId={currentPropertyId} currentPlan={hotelInfo.plan} onUpgrade={handleUpgrade} />",
"    )",
"",
"    if (view === 'INTEGRATIONS') return (",
"      <div className=\"space-y-6\">",
"        <div className=\"bg-surface border border-border rounded-2xl p-6 space-y-4\">",
"          <div><h3 className=\"text-base font-semibold text-white\">Integrations & Channels</h3><p className=\"text-xs text-text-secondary mt-0.5\">Connect OTA channels, payment gateways and communication tools</p></div>",
"          <div className=\"grid grid-cols-1 md:grid-cols-2 gap-3\">",
"            {INTEGRATIONS.map(intg => (",
"              <div key={intg.id} className=\"flex items-center justify-between p-4 bg-surface-light border border-border rounded-xl\">",
"                <div><p className=\"text-sm font-semibold text-white\">{intg.name}</p><p className=\"text-xs text-text-secondary mt-0.5\">{intg.type}</p></div>",
"                <div className=\"flex items-center gap-3\">",
"                  <span className={cn('text-xs font-semibold px-2.5 py-1 rounded-full', intg.status === 'CONNECTED' ? 'bg-emerald-500/15 text-emerald-400' : 'bg-surface text-text-tertiary border border-border')}>",
"                    {intg.status === 'CONNECTED' ? 'Connected' : 'Not Connected'}",
"                  </span>",
"                  <button className=\"text-xs text-primary hover:underline font-medium\">{intg.status === 'CONNECTED' ? 'Manage' : 'Connect'}</button>",
"                </div>",
"              </div>",
"            ))}",
"          </div>",
"          <div className=\"bg-amber-500/10 border border-amber-500/20 rounded-xl p-4\">",
"            <p className=\"text-xs text-amber-400 font-medium\">OTA channel sync requires the Standard or Enterprise plan. Contact support to enable.</p>",
"          </div>",
"        </div>",
"      </div>",
"    )",
"",
"    if (view === 'RETENTION') return (",
"      <div className=\"space-y-6\">",
"        <div className=\"bg-surface border border-border rounded-2xl p-6 space-y-5\">",
"          <div><h3 className=\"text-base font-semibold text-white\">Data Retention</h3><p className=\"text-xs text-text-secondary mt-0.5\">Configure how long different types of data are stored</p></div>",
"          <div className=\"grid grid-cols-1 md:grid-cols-2 gap-4\">",
"            <div><label className={lc}>Guest Profiles</label><select value={retention.guestProfiles} onChange={e => setRetention(p => ({ ...p, guestProfiles: e.target.value }))} className={cn(ic, 'appearance-none cursor-pointer')}><option value=\"1_YEAR\">1 Year</option><option value=\"3_YEARS\">3 Years</option><option value=\"5_YEARS\">5 Years</option><option value=\"FOREVER\">Forever</option></select></div>",
"            <div><label className={lc}>Financial Records</label><select value={retention.financials} onChange={e => setRetention(p => ({ ...p, financials: e.target.value }))} className={cn(ic, 'appearance-none cursor-pointer')}><option value=\"3_YEARS\">3 Years</option><option value=\"5_YEARS\">5 Years</option><option value=\"7_YEARS\">7 Years</option><option value=\"FOREVER\">Forever</option></select></div>",
"            <div><label className={lc}>Service Logs</label><select value={retention.serviceLogs} onChange={e => setRetention(p => ({ ...p, serviceLogs: e.target.value }))} className={cn(ic, 'appearance-none cursor-pointer')}><option value=\"30_DAYS\">30 Days</option><option value=\"90_DAYS\">90 Days</option><option value=\"1_YEAR\">1 Year</option><option value=\"3_YEARS\">3 Years</option></select></div>",
"          </div>",
"          <div className=\"flex items-center justify-between p-4 bg-surface-light border border-border rounded-xl\">",
"            <div><p className=\"text-sm font-medium text-white\">Legal Hold Mode</p><p className=\"text-xs text-text-secondary mt-0.5\">Prevent deletion of any data (for compliance/audit)</p></div>",
"            <Switch checked={retention.legalHoldMode} onChange={() => setRetention(p => ({ ...p, legalHoldMode: !p.legalHoldMode }))} />",
"          </div>",
"          <Button onClick={() => toast.success('Retention settings saved')} variant=\"primary\" className=\"text-sm\"><Save className=\"w-4 h-4 mr-2\" />Save Settings</Button>",
"        </div>",
"      </div>",
"    )",
"",
"    return (",
"      <div className=\"grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4\">",
"        {NAV.map(item => (",
"          <button key={item.id} onClick={() => setView(item.id.toUpperCase())}",
"            className=\"group p-5 bg-surface border border-border rounded-2xl text-left hover:border-primary/40 hover:bg-surface-light transition-all\">",
"            <div className=\"flex items-start justify-between mb-4\">",
"              <div className=\"w-10 h-10 rounded-xl bg-surface-light border border-border flex items-center justify-center text-text-secondary group-hover:text-primary group-hover:border-primary/30 transition-all\">",
"                <item.icon className=\"w-5 h-5\" />",
"              </div>",
"              <ChevronRight className=\"w-4 h-4 text-text-tertiary group-hover:text-primary transition-all group-hover:translate-x-0.5\" />",
"            </div>",
"            <h3 className=\"text-sm font-semibold text-white mb-1\">{item.label}</h3>",
"            <p className=\"text-xs text-text-secondary leading-relaxed\">{item.desc}</p>",
"          </button>",
"        ))}",
"      </div>",
"    )",
"  }",
"",
"  const viewTitle: Record<string, string> = {",
"    OVERVIEW: 'Settings', BRANDING: 'General Info', ROLES: 'Roles & Permissions',",
"    FINANCIAL: 'Financial & Tax', OPS: 'Notifications', SUBSCRIPTION: 'Subscription & Plans',",
"    INTEGRATIONS: 'Integrations', RETENTION: 'Data Retention',",
"  }",
"",
"  return (",
"    <div className=\"space-y-6\">",
"      <div className=\"flex items-center gap-4\">",
"        {view !== 'OVERVIEW' && (",
"          <button onClick={() => setView('OVERVIEW')} className=\"w-9 h-9 flex items-center justify-center rounded-xl bg-surface-light border border-border hover:border-primary/40 transition-all\">",
"            <ChevronLeft className=\"w-4 h-4 text-text-secondary\" />",
"          </button>",
"        )}",
"        <div>",
"          <h1 className=\"text-xl font-bold text-white\">{viewTitle[view] ?? view}</h1>",
"          {view !== 'OVERVIEW' && <p className=\"text-xs text-text-secondary mt-0.5\">{NAV.find(n => n.id.toUpperCase() === view)?.desc}</p>}",
"        </div>",
"      </div>",
"      {renderView()}",
"    </div>",
"  )",
"}",
]

with open('app/admin/settings/page.tsx', 'a', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')
print(f'renderView + return: {len(lines)} lines')
