lines = [
"",
"// ─── Financial Settings Component ───────────────────────────────────────────",
"function FinancialView({ propertyId }: { propertyId: string | null | undefined }) {",
"  const [s, setS] = useState({",
"    gstPercent: 18, serviceChargePercent: 0, luxuryTaxPercent: 0,",
"    defaultDiscountPercent: 0, discountLabel: 'Discount',",
"    invoicePrefix: 'INV', invoiceFooter: '',",
"    checkInTime: '14:00', checkOutTime: '11:00',",
"  })",
"  const [loading, setLoading] = useState(true)",
"  const [saving, setSaving] = useState(false)",
"",
"  useEffect(() => {",
"    if (!propertyId || propertyId === 'ALL') { setLoading(false); return }",
"    fetch(`/api/admin/settings/financial?propertyId=${propertyId}`)",
"      .then(r => r.json()).then(j => { if (j.success && j.data) setS(prev => ({ ...prev, ...j.data })) })",
"      .catch(() => {}).finally(() => setLoading(false))",
"  }, [propertyId])",
"",
"  const save = async () => {",
"    if (!propertyId || propertyId === 'ALL') { toast.error('Select a hotel first'); return }",
"    setSaving(true)",
"    try {",
"      const res = await fetch('/api/admin/settings/financial', {",
"        method: 'POST', headers: { 'Content-Type': 'application/json' },",
"        body: JSON.stringify({ propertyId, ...s }),",
"      })",
"      const j = await res.json()",
"      if (j.success) toast.success('Financial settings saved')",
"      else toast.error(j.error ?? 'Failed to save')",
"    } catch { toast.error('Connection error') } finally { setSaving(false) }",
"  }",
"",
"  if (loading) return (",
"    <div className=\"flex items-center justify-center h-48\">",
"      <Loader2 className=\"w-6 h-6 animate-spin text-primary\" />",
"    </div>",
"  )",
"",
"  const base = 5000",
"  const gst = base * s.gstPercent / 100",
"  const sc = base * s.serviceChargePercent / 100",
"  const lt = base * s.luxuryTaxPercent / 100",
"  const total = base + gst + sc + lt",
"  const disc = total * s.defaultDiscountPercent / 100",
"  const final = total - disc",
"",
"  const ic = 'w-full bg-surface-light border border-border rounded-xl px-4 py-2.5 text-sm text-white focus:ring-1 focus:ring-primary outline-none transition-all'",
"  const lc = 'text-xs font-semibold text-text-secondary block mb-1.5'",
"",
"  return (",
"    <div className=\"space-y-6\">",
"      <div className=\"bg-surface border border-border rounded-2xl p-6 space-y-6\">",
"        <div className=\"flex items-center justify-between\">",
"          <div>",
"            <h3 className=\"text-base font-semibold text-white\">Tax Rates</h3>",
"            <p className=\"text-xs text-text-secondary mt-0.5\">Applied automatically to every booking</p>",
"          </div>",
"          <Button onClick={save} loading={saving} variant=\"primary\" className=\"text-sm\">",
"            <Save className=\"w-4 h-4 mr-2\" /> Save",
"          </Button>",
"        </div>",
"        <div className=\"grid grid-cols-1 md:grid-cols-3 gap-4\">",
"          <div className=\"space-y-1.5\"><label className={lc}>GST %</label><p className=\"text-[11px] text-text-tertiary\">Goods &amp; Services Tax on room charges</p><input type=\"number\" value={s.gstPercent} onChange={e => setS(p => ({ ...p, gstPercent: parseFloat(e.target.value) || 0 }))} className={ic} /></div>",
"          <div className=\"space-y-1.5\"><label className={lc}>Service Charge %</label><p className=\"text-[11px] text-text-tertiary\">Hotel service charge</p><input type=\"number\" value={s.serviceChargePercent} onChange={e => setS(p => ({ ...p, serviceChargePercent: parseFloat(e.target.value) || 0 }))} className={ic} /></div>",
"          <div className=\"space-y-1.5\"><label className={lc}>Luxury Tax %</label><p className=\"text-[11px] text-text-tertiary\">State luxury tax</p><input type=\"number\" value={s.luxuryTaxPercent} onChange={e => setS(p => ({ ...p, luxuryTaxPercent: parseFloat(e.target.value) || 0 }))} className={ic} /></div>",
"        </div>",
"        <div className=\"grid grid-cols-1 md:grid-cols-2 gap-4\">",
"          <div className=\"space-y-1.5\"><label className={lc}>Default Discount %</label><p className=\"text-[11px] text-text-tertiary\">Auto-applied to all bookings (0 = none)</p><input type=\"number\" value={s.defaultDiscountPercent} onChange={e => setS(p => ({ ...p, defaultDiscountPercent: parseFloat(e.target.value) || 0 }))} className={ic} /></div>",
"          <div className=\"space-y-1.5\"><label className={lc}>Discount Label</label><p className=\"text-[11px] text-text-tertiary\">e.g. Early Bird, Member Rate</p><input type=\"text\" value={s.discountLabel} onChange={e => setS(p => ({ ...p, discountLabel: e.target.value }))} className={ic} /></div>",
"        </div>",
"      </div>",
"      <div className=\"bg-surface border border-border rounded-2xl p-6 space-y-4\">",
"        <h3 className=\"text-base font-semibold text-white\">Invoice Settings</h3>",
"        <div className=\"grid grid-cols-1 md:grid-cols-2 gap-4\">",
"          <div className=\"space-y-1.5\"><label className={lc}>Invoice Prefix</label><p className=\"text-[11px] text-text-tertiary\">e.g. INV, ZB, HTL</p><input type=\"text\" value={s.invoicePrefix} onChange={e => setS(p => ({ ...p, invoicePrefix: e.target.value }))} className={ic} /></div>",
"          <div className=\"space-y-1.5\"><label className={lc}>Invoice Footer Note</label><p className=\"text-[11px] text-text-tertiary\">Appears at the bottom of every invoice</p><input type=\"text\" value={s.invoiceFooter} onChange={e => setS(p => ({ ...p, invoiceFooter: e.target.value }))} className={ic} /></div>",
"        </div>",
"      </div>",
"      <div className=\"bg-surface border border-border rounded-2xl p-6 space-y-4\">",
"        <h3 className=\"text-base font-semibold text-white\">Check-in / Check-out Times</h3>",
"        <div className=\"grid grid-cols-1 md:grid-cols-2 gap-4\">",
"          <div className=\"space-y-1.5\"><label className={lc}>Check-in Time</label><input type=\"time\" value={s.checkInTime} onChange={e => setS(p => ({ ...p, checkInTime: e.target.value }))} className={ic} /></div>",
"          <div className=\"space-y-1.5\"><label className={lc}>Check-out Time</label><input type=\"time\" value={s.checkOutTime} onChange={e => setS(p => ({ ...p, checkOutTime: e.target.value }))} className={ic} /></div>",
"        </div>",
"      </div>",
"      <div className=\"bg-surface border border-border rounded-2xl p-6\">",
"        <h3 className=\"text-base font-semibold text-white mb-4\">Live Preview — ₹5,000 room charge</h3>",
"        <div className=\"space-y-2 text-sm\">",
"          <div className=\"flex justify-between text-text-secondary\"><span>Room Charges</span><span>₹{base.toLocaleString('en-IN')}</span></div>",
"          {gst > 0 && <div className=\"flex justify-between text-text-secondary\"><span>GST ({s.gstPercent}%)</span><span>+₹{gst.toLocaleString('en-IN', { maximumFractionDigits: 2 })}</span></div>}",
"          {sc > 0 && <div className=\"flex justify-between text-text-secondary\"><span>Service Charge ({s.serviceChargePercent}%)</span><span>+₹{sc.toLocaleString('en-IN', { maximumFractionDigits: 2 })}</span></div>}",
"          {lt > 0 && <div className=\"flex justify-between text-text-secondary\"><span>Luxury Tax ({s.luxuryTaxPercent}%)</span><span>+₹{lt.toLocaleString('en-IN', { maximumFractionDigits: 2 })}</span></div>}",
"          <div className=\"flex justify-between text-text-secondary border-t border-border pt-2\"><span>Subtotal</span><span>₹{total.toLocaleString('en-IN', { maximumFractionDigits: 2 })}</span></div>",
"          {disc > 0 && <div className=\"flex justify-between text-emerald-400\"><span>{s.discountLabel} ({s.defaultDiscountPercent}%)</span><span>-₹{disc.toLocaleString('en-IN', { maximumFractionDigits: 2 })}</span></div>}",
"          <div className=\"flex justify-between text-white font-bold border-t border-border pt-2\"><span>Guest Pays</span><span>₹{final.toLocaleString('en-IN', { maximumFractionDigits: 2 })}</span></div>",
"        </div>",
"      </div>",
"    </div>",
"  )",
"}",
]

with open('app/admin/settings/page.tsx', 'a', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')
print(f'Financial component: {len(lines)} lines appended')
