lines = [
"",
"// ─── Subscription Component ──────────────────────────────────────────────────",
"function SubscriptionView({ propertyId, currentPlan, onUpgrade }: {",
"  propertyId: string | null | undefined",
"  currentPlan: string",
"  onUpgrade: (plan: PlanDef) => void",
"}) {",
"  const [plans, setPlans] = useState<PlanDef[]>([])",
"  const [loading, setLoading] = useState(true)",
"",
"  useEffect(() => {",
"    fetch('/api/admin/subscription-plans')",
"      .then(r => r.json())",
"      .then(j => { if (j.success) setPlans(j.data) })",
"      .catch(() => {})",
"      .finally(() => setLoading(false))",
"  }, [])",
"",
"  if (loading) return (",
"    <div className=\"flex items-center justify-center h-48\">",
"      <Loader2 className=\"w-6 h-6 animate-spin text-primary\" />",
"    </div>",
"  )",
"",
"  const activePlan = plans.find(p => p.plan === currentPlan)",
"",
"  return (",
"    <div className=\"space-y-6\">",
"      {activePlan && (",
"        <div className=\"bg-primary/10 border border-primary/30 rounded-2xl p-5 flex items-center justify-between\">",
"          <div className=\"flex items-center gap-3\">",
"            {(() => { const Icon = PLAN_ICONS[activePlan.plan] ?? Star; return <Icon className={cn('w-6 h-6', PLAN_COLORS[activePlan.plan] ?? 'text-primary')} /> })()}",
"            <div>",
"              <p className=\"text-xs font-semibold text-text-secondary uppercase tracking-wider\">Current Plan</p>",
"              <p className=\"text-lg font-bold text-white\">{activePlan.displayName}</p>",
"              {activePlan.tagline && <p className=\"text-xs text-text-secondary mt-0.5\">{activePlan.tagline}</p>}",
"            </div>",
"          </div>",
"          <div className=\"text-right\">",
"            {activePlan.plan !== 'ENTERPRISE' ? (",
"              <div>",
"                <p className=\"text-xl font-bold text-white\">",
"                  ₹{activePlan.discountedPrice.toLocaleString('en-IN')}",
"                  <span className=\"text-xs text-text-tertiary font-normal\">/mo</span>",
"                </p>",
"                {activePlan.maxRooms > 0 && <p className=\"text-xs text-text-secondary mt-0.5\">Up to {activePlan.maxRooms} rooms</p>}",
"              </div>",
"            ) : (",
"              <p className=\"text-base font-bold text-white\">Custom Pricing</p>",
"            )}",
"          </div>",
"        </div>",
"      )}",
"",
"      <div>",
"        <h3 className=\"text-sm font-semibold text-text-secondary mb-4\">All Plans</h3>",
"        <div className=\"grid grid-cols-1 md:grid-cols-2 gap-4\">",
"          {plans.map(plan => {",
"            const Icon = PLAN_ICONS[plan.plan] ?? Star",
"            const isActive = plan.plan === currentPlan",
"            const savings = plan.originalPrice - plan.discountedPrice",
"            return (",
"              <div key={plan.plan} className={cn(",
"                'relative border rounded-2xl p-5 transition-all',",
"                isActive ? 'bg-primary/10 border-primary/40 ring-1 ring-primary/20' : 'bg-surface border-border hover:border-primary/30'",
"              )}>",
"                {isActive && (",
"                  <span className=\"absolute top-3 right-3 text-[10px] font-bold bg-primary text-white px-2 py-0.5 rounded-full uppercase tracking-wider\">Active</span>",
"                )}",
"                <div className=\"flex items-start gap-3 mb-3\">",
"                  <div className={cn('w-9 h-9 rounded-xl flex items-center justify-center shrink-0', isActive ? 'bg-primary/20' : 'bg-surface-light')}>",
"                    <Icon className={cn('w-4 h-4', PLAN_COLORS[plan.plan] ?? 'text-primary')} />",
"                  </div>",
"                  <div>",
"                    <h4 className=\"text-sm font-bold text-white\">{plan.displayName}</h4>",
"                    {plan.tagline && <p className=\"text-[11px] text-text-secondary mt-0.5\">{plan.tagline}</p>}",
"                  </div>",
"                </div>",
"                {plan.plan !== 'ENTERPRISE' ? (",
"                  <div className=\"mb-3\">",
"                    <div className=\"flex items-baseline gap-2\">",
"                      <span className=\"text-xl font-bold text-white\">₹{plan.discountedPrice.toLocaleString('en-IN')}</span>",
"                      <span className=\"text-xs text-text-tertiary\">/month</span>",
"                    </div>",
"                    {savings > 0 && (",
"                      <div className=\"flex items-center gap-2 mt-1\">",
"                        <span className=\"text-xs text-text-tertiary line-through\">₹{plan.originalPrice.toLocaleString('en-IN')}</span>",
"                        <span className=\"text-[10px] font-bold text-emerald-400 bg-emerald-400/10 px-1.5 py-0.5 rounded\">{plan.discountPercent}% OFF</span>",
"                      </div>",
"                    )}",
"                  </div>",
"                ) : (",
"                  <div className=\"mb-3 flex items-center gap-2\">",
"                    <span className=\"text-sm font-bold text-white\">Custom Pricing</span>",
"                  </div>",
"                )}",
"                <div className=\"flex items-center gap-4 mb-3 text-xs text-text-secondary\">",
"                  <span className=\"flex items-center gap-1\"><BedDouble className=\"w-3.5 h-3.5\" />{plan.maxRooms === 0 ? 'Unlimited rooms' : `Up to ${plan.maxRooms} rooms`}</span>",
"                  <span className=\"flex items-center gap-1\"><Users className=\"w-3.5 h-3.5\" />{plan.maxStaff === 0 ? 'Unlimited staff' : `Up to ${plan.maxStaff} staff`}</span>",
"                </div>",
"                <div className=\"space-y-1 mb-4\">",
"                  {plan.features.slice(0, 5).map(f => (",
"                    <div key={f} className=\"flex items-center gap-2 text-[11px] text-text-secondary\">",
"                      <CheckCircle2 className={cn('w-3.5 h-3.5 shrink-0', PLAN_COLORS[plan.plan] ?? 'text-primary')} />",
"                      {f.replace(/_/g, ' ').toLowerCase().replace(/\\b\\w/g, (c: string) => c.toUpperCase())}",
"                    </div>",
"                  ))}",
"                  {plan.features.length > 5 && <p className=\"text-[11px] text-text-tertiary pl-5\">+{plan.features.length - 5} more features</p>}",
"                </div>",
"                {isActive ? (",
"                  <div className=\"flex items-center gap-2 text-xs text-primary font-semibold\">",
"                    <Check className=\"w-4 h-4\" /> Current Plan",
"                  </div>",
"                ) : plan.plan === 'ENTERPRISE' ? (",
"                  <a href=\"mailto:sales@zenbourg.com\" className=\"block w-full text-center py-2.5 rounded-xl border border-purple-500/30 text-purple-400 text-xs font-semibold hover:bg-purple-500/10 transition-all\">",
"                    Contact Sales",
"                  </a>",
"                ) : (",
"                  <button onClick={() => onUpgrade(plan)} className=\"w-full py-2.5 rounded-xl bg-primary text-white text-xs font-semibold hover:bg-primary/90 transition-all flex items-center justify-center gap-2\">",
"                    Upgrade to {plan.displayName}",
"                  </button>",
"                )}",
"              </div>",
"            )",
"          })}",
"        </div>",
"      </div>",
"      {plans.length === 0 && (",
"        <div className=\"text-center py-12 text-text-tertiary text-sm\">",
"          <ShieldAlert className=\"w-8 h-8 mx-auto mb-3 opacity-40\" />",
"          No plans available",
"        </div>",
"      )}",
"    </div>",
"  )",
"}",
]

with open('app/admin/settings/page.tsx', 'a', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')
print(f'Subscription component: {len(lines)} lines')
