import os

lines = []

# Part 1: imports and types
lines += [
"'use client'",
"",
"import { useState, useEffect, useCallback, useMemo } from 'react'",
"import { useSession } from 'next-auth/react'",
"import {",
"  Save, Building2, IndianRupee, Sparkles, Shield, Smartphone,",
"  Database, Globe, ChevronRight, ChevronLeft, Loader2,",
"  Calendar, Check, CheckCircle2, Bell, Zap, ShieldAlert, ClipboardList,",
"  Star, Crown, BedDouble, Users",
"} from 'lucide-react'",
"import { cn } from '@/lib/utils'",
"import { toast } from 'sonner'",
"import { getAdminContext } from '@/lib/admin-context'",
"import Switch from '@/components/ui/Switch'",
"import Button from '@/components/ui/Button'",
"",
"interface HotelInfo {",
"  name: string; description: string; address: string; phone: string; email: string",
"  plan: string; features: string[]; planExpiresAt: string | null; ranking: number",
"}",
"interface PlanDef {",
"  id?: string; plan: string; displayName: string; tagline?: string; description?: string",
"  originalPrice: number; discountedPrice: number; discountPercent: number",
"  maxRooms: number; maxStaff: number; features: string[]",
"}",
"",
"const NAV = [",
"  { id: 'branding',     label: 'General Info',         icon: Building2,   desc: 'Hotel name, address, contact details' },",
"  { id: 'roles',        label: 'Roles & Permissions',  icon: Shield,      desc: 'Staff access levels per module' },",
"  { id: 'financial',    label: 'Financial & Tax',      icon: IndianRupee, desc: 'GST, service charge, discounts, invoice' },",
"  { id: 'ops',          label: 'Notifications',        icon: Smartphone,  desc: 'SMS, push, email alert settings' },",
"  { id: 'subscription', label: 'Subscription & Plans', icon: Sparkles,    desc: 'Current plan, upgrade, billing' },",
"  { id: 'integrations', label: 'Integrations',         icon: Globe,       desc: 'OTA channels and API connections' },",
"  { id: 'retention',    label: 'Data Retention',       icon: Database,    desc: 'How long data is stored' },",
"]",
"",
"const PERMISSIONS_SCHEMA = [",
"  { id: 'reservations', label: 'Reservations', icon: Calendar, permissions: [",
"    { id: 'view_reservations',  label: 'View Reservations',   desc: 'View booking calendar and lists' },",
"    { id: 'create_reservation', label: 'Create Reservation',  desc: 'Add new bookings manually' },",
"    { id: 'edit_guest_details', label: 'Edit Guest Details',  desc: 'Modify guest names and contact info' },",
"    { id: 'process_refunds',    label: 'Process Refunds',     desc: 'Authorize refunds to guests' },",
"  ]},",
"  { id: 'housekeeping', label: 'Housekeeping', icon: ClipboardList, permissions: [",
"    { id: 'view_room_status',   label: 'View Room Status',   desc: 'See clean/dirty/inspected status' },",
"    { id: 'update_room_status', label: 'Update Room Status', desc: 'Change room status' },",
"    { id: 'manage_supplies',    label: 'Manage Supplies',    desc: 'Track and order cleaning supplies' },",
"  ]},",
"  { id: 'finance', label: 'Finance', icon: IndianRupee, permissions: [",
"    { id: 'view_reports',    label: 'View Financial Reports', desc: 'Access revenue reports' },",
"    { id: 'manage_invoices', label: 'Manage Invoices',        desc: 'Create and edit guest invoices' },",
"    { id: 'tax_settings',    label: 'Manage Tax Rules',       desc: 'Configure tax rates' },",
"  ]},",
"]",
"",
"const ROLES = [",
"  { id: 'HOTEL_ADMIN',  label: 'Hotel Admin',  desc: 'Full property management' },",
"  { id: 'MANAGER',      label: 'Manager',      desc: 'Operations and staff oversight' },",
"  { id: 'RECEPTIONIST', label: 'Receptionist', desc: 'Front desk and check-in' },",
"  { id: 'STAFF',        label: 'Staff',        desc: 'Task execution only' },",
"]",
"",
"const PLAN_ICONS: Record<string, React.ElementType> = {",
"  BASE: Building2, STARTER: Zap, STANDARD: Star, ENTERPRISE: Crown,",
"  GOLD: Star, PLATINUM: Shield, DIAMOND: Sparkles,",
"}",
"const PLAN_COLORS: Record<string, string> = {",
"  BASE: 'text-slate-400', STARTER: 'text-blue-400',",
"  STANDARD: 'text-amber-400', ENTERPRISE: 'text-purple-400',",
"  GOLD: 'text-amber-400', PLATINUM: 'text-blue-400', DIAMOND: 'text-purple-400',",
"}",
]

with open('app/admin/settings/page.tsx', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')
print(f'Written {len(lines)} lines')
